### PR TITLE
Clean up scribusdoc.cpp & scribusdoc.h

### PR DESCRIPTION
**Pull request by asmaAL-Bahanta**

### CODE REVIEW

**Comment by aoloe** [comment]
hey asma, thanks for the PR!
if you have read the previous discussions in this repository, you will know that we cannot accept PR in this repository.
but we are glad to get them and we will work with you to make sure that the patch is correct and then get it into the bug tracker and let it be judged by the team!

in my experience, the team does not always like when outcommented code is removed by contributors... but we might try, submit this patch to the bug tracker and see the reaction...

**Comment by luzpaz** [comment]
@asmaAL-Bahanta thanks for the PR :)
 
> in my experience, the team does not always like when outcommented code is removed by contributors... but we might try, submit this patch to the bug tracker and see the reaction...  
@asmaAL-Bahanta I think if you elaborated on why you think those comments need to be removed would be further helpful for the team to understand your logic.

**Comment by asmaAL-Bahanta** [comment]
@luzpaz @aoloe 
removing dead code, unused variables, uncalled functions...etc would make the code more organized and readable.

**Comment by aoloe** [comment]
@asmaAL-Bahanta i 100% agree with you! (and @luzpaz cannot code... but i will explain him what the issue later :-)

i've skimmed through your PR and you seem to only have removed outcommented code and i've not seen any comment from the original programmers explaining why that code should stay in.

i think we can try to create a diff file from the PR, and submit it to the scribus tracker and see how the team reacts to it!
can you do it?

**Comment by luzpaz** [comment]
Thank @asmaAL-Bahanta !!! 
Your patches were committed in r20692 (755cc842f9e273558fab9fdde649bd1b7b4fcfd2)
reference: http://bugs.scribus.net/view.php?id=13544

**Pull request closed without merging**
