### PR TITLE
prefix private member of class CanvasMode_CopyProperties

### PR DESCRIPTION
**Pull request by AliYousuf**

### CODE REVIEW

**Comment by aoloe** [comment]
hey ali, thanks for the PR!
if you have read the previous discussions in this repository, you will know that we cannot accept PR in this repository.
but we are glad to get them and we will work with you to make sure that the patch is correct and then get it into the bug tracker and let it be judged by the team!

i've skimmed through your PR and it basically looks fine.
since mrB wants the 'm_'s to be used everywhere it's indeed better to track them down and make them uniform.
i would not do it in all files at once, but if you're working on that module and have a hard time figuring out what's going on, it's a good idea to submit a patch for it!

i have only one remark: you are proposing `MoveGX > m_MoveGX`.
i would suggest you `MoveGX > m_moveGX`.
members normal normally start with a lowercase... except if you see a good reason my that `M` should be capitalized :-)

finally, Travis is working on your patch and if it reports a success, we will know that what you did is probably correct! (or at least that it compiles...)

**Comment by luzpaz** [comment]
@AliYousuf thanks for the PR. I echo what @aoloe has written. It looks like Travis builds the PR correctly. Please just address @aoloe comments:
> have only one remark: you are proposing ```MoveGX > m_MoveGX```.
i would suggest you ```MoveGX > m_moveGX```.
members normal normally start with a lowercase... except if you see a good reason my that M should be capitalized :-)

Then we can submit this PR as a diff (https://github.com/scribusproject/scribus/pull/36.diff) to the bugtracker.

**Comment by aoloe** [comment]
@luzpaz well, @AliYousuf  does not have to do it!
the PR is fine as is (since it passed the CI)
but he could think about the case and check if it would not be better to rename all members to start with a lowercase letter (with exceptions! there might me members that would look strange in lower case... i can thing that `m_GX` is such a case: i've not checked what the meaning of "G" is, but under certain circumstances `m_gX` would look strange).

**Comment by luzpaz** [comment]
First batch was committed in cc801c68c8fbf0ef0a7ae2660124b128ed1731dc (r20577)

Second batch committed in 1ae42a5bc230433a75059436e728e2f2cfc81ef9 (r20593)

**Comment by AliYousuf** [comment]
http://bugs.scribus.net/view.php?id=13556

**Comment by luzpaz** [comment]
Thanks @AliYousuf !!! This was committed to Scribus trunk 2016-01-17 in r20691

**Pull request closed without merging**
