### PR TITLE
Add hungarian translators

### PR DESCRIPTION
**Pull request by gyuris**
Add Benedek Péter and Heim Tibor

### CODE REVIEW

**Comment by gyuris** [comment]
Heim Tibor: https://www.transifex.com/user/profile/Htibi/
Benedek Péter: https://www.transifex.com/user/profile/Bendeg%C3%BAz/

**Comment by luzpaz** [comment]
@gyuris thanks. I'm re-writing that file because many changes need to be made. I will make this notation as well. Cheers. Closing this for now.

**Comment by gyuris** [comment]
@luzpaz, please add this to your pull request d9fb618a5e014c4e7eb70d56a49acc3aa72998c3

**Comment by luzpaz** [comment]
@gyuris don't worry, didn't forget you. I'm adding Translators in the next patch (phase 2)

**Comment by luzpaz** [comment]
reference: http://bugs.scribus.net/view.php?id=13711

**Comment by luzpaz** [comment]
PR https://github.com/scribusproject/scribus/pull/46

**Comment by gyuris** [comment]
Thanks!

**Comment by luzpaz** [comment]
merged in 7a7e5ce83c0dffbe6e877ceafb119f5a9d110620
Thanks for all your work fellas!

**Pull request closed without merging**
