### PR TITLE
Better HiRes support

### PR DESCRIPTION
**Pull request by LiamHD**
Add basic HiRes support on Mac OS.

### CODE REVIEW

**Comment by LiamHD** [comment]
See the difference:
new_old

**Comment by luzpaz** [comment]
Hi @LiamHD 
Help me understand the differences in the screenshot. I'm not picking up on them.

**Comment by LiamHD** [comment]
@luzpaz 
Just click on the screenshot (so that you see the full size version). You will see that the text on the left side is sharp compared to the text on the right side.

**Comment by luzpaz** [comment]
@LiamHD Great! I submitted patch to the scribus bugtracker http://bugs.scribus.net/view.php?id=13301

**Comment by luzpaz** [comment]
@LiamHD patch was committed upstream and now is in github mirror (https://github.com/scribusproject/scribus/commit/156ebfdefce35adb484ed35a48b95bd42afb1970). Thanks for your PR!

**Comment by LiamHD** [comment]
Thanks.
How often do you mirror from SVN to githup? Is this a manual process?

What's the best / easiest way if I want to contribute code and want to develop on my Macbook?
I would love to use the git repo (as I use git in all my other projects and don't know SVN). Is that possible?

**Comment by luzpaz** [comment]
@LiamHD we mirror it manually, at this point. @aoloe or myself will trigger the sync using a script that @chhitz created. 

> What's the best / easiest way if I want to contribute code and want to develop on my Macbook?  
The main devs of Scribus prefer to use SVN. The workflow is to submit any bugs, patches via bugs.scribus.net and then those in turn are committed via SVN. 
One of the main devs, Craig, uses OSX. 

> I would love to use the git repo (as I use git in all my other projects and don't know SVN). Is that possible?
I totally think so! What we would do is translate any of your PRs in to bugs.scribus.net [like we did with this issue](http://bugs.scribus.net/view.php?id=13301). It went fairly smooth though obviously not as ideal as approving a PR directly. This will work for now.

**Comment by LiamHD** [comment]
So I would install the dependencies of scribus via homebrew and then clone the git repo?
Would I use XCode as IDE?

I looked around on your wiki but could not find something like a "getting started guide" for developers.

**Comment by aoloe** [comment]
hi @LiamHD,

something still missing in our github workflow: how to mark the pull requests as accepted, even if we cannot apply them to the master... there must be a way :-)
if you can find it out for us, it would be a nice contribution.

for the IDE, the best one for scribus is probably Qt Craetor: http://wiki.qt.io/Category:Tools::QtCreator
it's provided by the company developing Qt, is not perfect, but imo rather good...

and concerning, the getting started guide, i have somewhere in my github account some notes about it :-) ... and there are older howtos in the wiki...

my notes are here:

- https://github.com/aoloe/libregraphics-manual-scribus-development
- https://github.com/aoloe/scribus-manual-development/

and you're welcome to make pull requests against them (most of all against the https://github.com/aoloe/scribus-manual-development/tree/master/content directory where the content should go at the end of the process).

some ideas on the way i'd like to setup the content can be found here:

- https://github.com/aoloe/scribus-manual-help-free/blob/master/CONTRIBUTING.md

everything still in the starting blocks...

**Comment by LiamHD** [comment]
regarding the github workflow.
Do you now that github repos can be cloned as svn repos? See https://github.com/blog/966-improved-subversion-client-support

**Comment by aoloe** [comment]
hi @LiamHD , everything has been tried.

until the next stable version 1.6 comes out there is not much use in discussing a switch to git/github with the scribus team. (at least for what i am concerned :-)

until that (unknown) time (in the future) this github repository will be managed as a community repository and patches will be handed hover to the team by attaching them to tickets in the official bug tracker.
the topic has been discussed at length and, personally, i'm more than happy that we finally seem to be able to manage a community repository on github!
and the first pull requests are coming in!

the next step being: a way to accept pull requests so that contributors get rewarded with nice stats in their account!
(the step after that might be to apply patches to the community version, that are not in the trunk... but we don't have such patches to apply right now... so it's an hypothetical thing for now)

**Comment by aoloe** [comment]
i have merged all my dev notes into https://github.com/aoloe/scribus-manual-development.

https://github.com/aoloe/libregraphics-manual-scribus-development should now really be depracated.

**Comment by LiamHD** [comment]
Ok that's quite basic. I would like to see how the local development setup ideally looks like (on the various platforms). As I do not have any experience in developing Scribus (on any platform) I don't feel capable of contributing this. 
As one of the main devs is developing on Mac OS maybe he can share how his setup looks like.

**Pull request closed without merging**
