### PR TITLE
Start generating Appimages for Master (Thanks to Host-Oman)

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
@probonopd any assistance would be much appreciated.

**Comment by probonopd** [comment]
@luzpaz I don't understand what you are trying to do with `.local/`.

**Comment by probonopd** [comment]
Also see https://github.com/nitramr/scribus-indigo/blob/master/AppImage-package/bundle.sh

**Comment by luzpaz** [comment]
Success! Waiting for core-devs to merge

**Comment by sommerluk** [comment]
Does this also include python? For me, the AppImage of the CTL branch did never work because of python.

References:
A workaround that does unfortunally not work for openSUSE: https://github.com/nitramr/scribus-indigo/issues/19#issuecomment-260130662
Relocable?: https://github.com/HOST-Oman/scribus/issues/215#issuecomment-260566334

**Comment by probonopd** [comment]
This build bundles `usr/lib/libpython2.7.so.1.0`. You can download the AppImage from the Travis CI build, the [URL](https://transfer.sh/FsFaW/scribus-git269f1e9-glibc2.14-x86-64.appimage) is in the Travis CI build log.

**Comment by gyuris** [comment]
Can we add translations from Transifex to Appimage? So it would be good for translators too. 
We have a script: https://github.com/scribusproject/scribus-translations/blob/master/update_transifex.sh

**Comment by probonopd** [comment]
Sure, why not. Where do they need to go for Scribus to pick them up?

**Comment by gyuris** [comment]
`/usr/share/scribus/translations/`
There is currently one file: `scribus.en_US.qm`
And please make [`lrelease`](http://doc.qt.io/qt-4.8/linguist-manager.html#lrelease) to produce .qm files from .ts files.
Thanks!

@luzpaz, what should we do with directly maintained languages?

**Comment by sommerluk** [comment]
With scribus-git269f1e9-glibc2.14-x86-64.appimage still a crash on openSUSE 42.1:
```realPath called with a relative path './share/pixmaps/', please fix
realPath called with a relative path './share/icons/', please fix
realPath called with a relative path './share/pixmaps/', please fix
realPath called with a relative path './share/icons/', please fix
pci id for fd 11: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
pathForIcon: Unable to load icon ././/share/scribus/icons/1_5_1/AppIcon.png: File not found
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
Scribus Crash
-------------
Scribus crashes due to Signal #11
Speicherzugriffsfehler
```

**Comment by luzpaz** [comment]
@gyuris lets open a separate ticket for appimage and transifex translations to discuss such things

**Comment by probonopd** [comment]
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
```
Argh, it's not finding the Python libraries. Do you also see this with the ones from https://bintray.com/probono/AppImages/Scribus#files?

**Comment by luzpaz** [comment]
@plinnell committed PR in 9a7ff99249ff32bdc0e1ad2bbad408270351084d 23110c3b96cf535a3a0c7a5be223b39a05ae7b00

**Comment by sommerluk** [comment]
From https://bintray.com/probono/AppImages/Scribus#files? coming Scribus-1.5.3.svn.21360-x86_64.AppImage is working fine at openSUSE.

However, the recent version from https://travis-ci.org/scribusproject/scribus/jobs/187868610 does not work.

**Comment by luzpaz** [comment]
@probonopd as per https://github.com/scribusproject/scribus/pull/78#issuecomment-269861229

>From https://bintray.com/probono/AppImages/Scribus#files? coming Scribus-1.5.3.svn.21360-x86_64.AppImage is working fine at openSUSE.
>
>However, the recent version from https://travis-ci.org/scribusproject/scribus/jobs/187868610 does not work.

**Comment by probonopd** [comment]
@luzpaz Possibly 
```
find . -type f -exec sed -i -e 's|/usr|././|g' {} \;
```
is needed in order to make Python use relative rather than absolute paths for finding its libraries.

At least that is what I did [here](https://github.com/probonopd/AppImages/blob/85e3dbea930220eec0bad8db19ab2fd931fd2f4d/recipes/scribus/Recipe#L323-L324).

**Comment by luzpaz** [comment]
@probonopd since you've updated the recipe on your end, should the builds now work correctly, or do I need to add that in to bundle.sh ?

**Comment by probonopd** [comment]
Please add it, instead of [line 93](https://github.com/scribusproject/scribus/pull/78/files#diff-9da923cc0c2f471166b0abe4504156e7R93) ff.

**Comment by luzpaz** [comment]
hmm.. need to close the PR and open a new one with @probonopd fix in https://github.com/scribusproject/scribus/pull/78#issuecomment-269864187

**Comment by luzpaz** [comment]
@probonopd should it look like: https://github.com/scribusproject/scribus/pull/78/commits/6f72aa9dce58aba5f6d56f7e2dbfaf4fa429d488 ?

**Comment by probonopd** [comment]
Looks good. If this is not sufficient we might need to leave away the `-exec`. Also the two lines following the new line are no longer needed because the added line will patch these files as well.

**Comment by luzpaz** [comment]
@plinnell or @MrB74 please follow feedback @probonopd gives from https://github.com/scribusproject/scribus/pull/78#issuecomment-269864187 and onward. so appimages work correctly.

**Comment by probonopd** [comment]
Looking at [this](http://lists.scribus.net/pipermail/scribus/2017-February/054069.html), it seems like this should be reopened.

**Pull request closed without merging**
