### PR TITLE
printdialog: only includes cups.h with HAVE_CUPS.

### PR DESCRIPTION
**Pull request by korli**

### CODE REVIEW

**Comment by aoloe** [comment]
hi

thanks for the patch...

may i ask, what problem it does solve?

from my understanding, if it's not windows and there is no cups, there is no use in enabling the print dialog...
and the switch should me moved elsewhere (cmake, print signals and slots...)
i guess that currently CUPS is mandatory on "non-windows" platforms...

**Comment by korli** [comment]
If you have a look at the 1.4.x branch, the same patch is already present there. And Cups is already checked in the rest of the source file.

**Comment by korli** [comment]
Haiku doesn't implement Cups, one can print to a file though.

**Comment by aoloe** [comment]
I don't know, I'm not really convinced about the usefulness of being able to print to a file from Scribus (printing through CUPS is unreliable anyway and should IMO be removed).
But i'll link this patch in the official bug tracker and we will see.

**Comment by aoloe** [comment]
https://bugs.scribus.net/view.php?id=14620

**Comment by aoloe** [comment]
it's in!

https://github.com/scribusproject/scribus/commit/61c6ee7b88abc36bb2b6e07aa829283322868e8b

technically, we cannot (yet) accept pull request, so i cannot do more than thank you and close this ticket...

**Comment by korli** [comment]
Thanks! I've also a patch specific to Haiku available here (I hope it applies on trunk) https://github.com/haikuports/haikuports/blob/master/app-office/scribus/patches/scribus-1.5.2.patchset
Shall I open another PR? I understand it's preferred to open an issue in the bug tracker, so I can also do that.

**Comment by aoloe** [comment]
hi korli, yes the official bug tracker is the only way to get a patch accepted into scribus... : - )

of course, things can be discussed and proposed elsewhere, but -- at the end -- what counts is the ticket in there.

**Pull request closed without merging**
