### PR TITLE
fix travis ci workflow

### PR DESCRIPTION
**Pull request by t0b3**
Closes: https://github.com/scribusproject/scribus/issues/107

### CODE REVIEW

**Comment by aoloe** [comment]
i've posted the diff with the request probono made on gitlab...

https://bugs.scribus.net/view.php?id=16107

i guess it's your pr that he has forwarded...

thanks!

**Comment by aoloe** [comment]
the patch has been applied.

https://bugs.scribus.net/view.php?id=16107
https://github.com/scribusproject/scribus/commit/356453ff23775dbae0ca42d0443873d5240e694e

thanks for submitting it.

if there are further issues, you're welcome to open a new pull requst : - )

**Comment by aoloe** [comment]
we cannot accept pull request as such, sorry.
closing.

**Comment by t0b3** [comment]
> the patch has been applied.
> 
> https://bugs.scribus.net/view.php?id=16107
> [356453f](https://github.com/scribusproject/scribus/commit/356453ff23775dbae0ca42d0443873d5240e694e)
> 
> thanks for submitting it.
> 
> if there are further issues, you're welcome to open a new pull request : - )

great. thx!

**Pull request closed without merging**
